# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=200, unique=True, validators=[tweets.validators.clean_content]),
        ),
    ]
