# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 03:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('abc', django.db.models.manager.Manager()),
            ],
        ),
    ]
